---
resources:
- name: concourse-test-1
  type: git
  source:
    uri: https://github.com/Hectim/concourse-test-1.git

- name: concourse-test-2
  type: git
  source:
    uri: https://github.com/Hectim/concourse-test-2.git

jobs:
- name: set-pipeline
  plan:
  - get: concourse-test-1
    trigger: true
  - task: set-pipeline
    file: concourse-test-1/set-pipeline.yml

- name: hello-world
  plan:
  - get: concourse-test-2
    trigger: true
  - task: output-hello-world
    file: concourse-test-2/hello-world-test.yml

- name: test-box
  plan:
  - get: concourse-test-1
    trigger: true
  - task: run-tests
    file: concourse-test-1/run-test.yml
